version: '3'
services:
  vsftpd:
    image: fauria/vsftpd:latest
    container_name: vsftp
    volumes:
      - /data/vsftp/ftp:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=user
      - FTP_PASS=123456
      - PASV_ENABLE=NO
