version: '3'

services:
  postgis:
    image: postgis/postgis:12-3.2
    container_name: postgis
    restart: always
    privileged: true

    ports:
    - "2069:5432"

    environment:
      # 使用上海时区
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test

    volumes:
      - ./postgres_data:/var/lib/postgresql/data