version: '3'

services:
  postgis:
    image: postgis/postgis:9.6-2.5
    restart: always
    privileged: true

    ports:
    - "2069:5432"

    environment:
      - POSTGRES_PASS=123456
      - POSTGRES_DBNAME=test
    volumes:
      - ./postgres_data:/var/lib/postgresql/data