version: "3"
services:
  postgres:
    image: postgres:12.6
    container_name: postgres
    restart: always

    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=test

    ports:
      - "5432:5432"

    volumes:
      - ./data:/var/lib/postgresql/data
