version: '3'
services:
  geoserver:
    image: geoserver:2.21.1-arm
    container_name: geoserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms256m -Xmx1g
    volumes:
      - "./geoserver_data:/opt/geoserver_data/"
      - "./additional_libs:/opt/additional_libs"