version: '3'
services:
  kong:
    image: kong:2.2.1-ubuntu
    container_name: kong
    restart: always
    privileged: true

    environment:
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong_postgres_user
      KONG_PG_PASSWORD: kong_postgres_password
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr

    depends_on:
      - kong-database

    ports:
      - "9000:8000"
      - "9001:8001"
      - "9443:8443"
      - "9444:8444"

  kong-database:
    image: postgres:9.6
    container_name: kong-database
    restart: always
    privileged: true

    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong_postgres_user
      POSTGRES_PASSWORD: kong_postgres_password

    ports:
      - "9002:5432"

    volumes:
      - /data/kong/data/postgresql:/var/lib/postgresql/data

  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: always
    privileged: true

    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_DATABASE: konga
      DB_USER: kong_postgres_user
      DB_PASSWORD: kong_postgres_password
      NODE_ENV: production

    depends_on:
      - kong
      - kong-database

    ports:
      - "9003:1337"
