version: '3'
services:
  minio1:
    image: minio/minio:RELEASE.2022-03-26T06-49-28Z
    container_name: minio1
    hostname: minio1
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data/minio1/data1:/data1
      - ./data/minio1/data2:/data2

    command: server http://minio{1...2}/data{1...2} http://minio{3...4}/data{1...2}  --console-address ":9001"

  minio2:
    image: minio/minio:RELEASE.2022-03-26T06-49-28Z
    container_name: minio2
    hostname: minio2
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data/minio2/data1:/data1
      - ./data/minio2/data2:/data2

    command: server http://minio{1...2}/data{1...2} http://minio{3...4}/data{1...2} --console-address ":9001"

  minio3:
    image: minio/minio:RELEASE.2022-03-26T06-49-28Z
    container_name: minio3
    hostname: minio3
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data/minio3/data1:/data1
      - ./data/minio3/data2:/data2

    command: server http://minio{1...2}/data{1...2} http://minio{3...4}/data{1...2}  --console-address ":9001"

  minio4:
    image: minio/minio:RELEASE.2022-03-26T06-49-28Z
    container_name: minio4
    hostname: minio4
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data/minio4/data1:/data1
      - ./data/minio4/data2:/data2

    command: server http://minio{1...2}/data{1...2} http://minio{3...4}/data{1...2}  --console-address ":9001"

  nginx:
    image: nginx:1.19.2-alpine
    container_name: minio-nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9900:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4


networks:
  default:
    external:
      name: minio