version: "3"
services:
  docker_in_docker:
    image: python:3.9-slim-bullseye
    container_name: docker_in_docker
    restart: always
    privileged: true

    command:
      - bash
      - -c
      - sleep 10d

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker